name: Sprint Development

on:
  workflow_dispatch:
    inputs:
      test_cases:
        description: 'Test cases to run (e.g., LoginTests#testLogin+testLogout,SignupTests#testSignup)'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Run Selected testCases using maven using workflow
        continue-on-error: true
        run: |
          echo "Running the following test cases:"
          echo "${{ github.event.inputs.test_cases }}"
          mvn test -Dtest="${{ github.event.inputs.test_cases }}"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Reports
        uses: simple-elf/allure-report-action@v1
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          retention_period: 5

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Sending Emails
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 465
          smtp-secure: true
          from-email: shailamore.qa@gmail.com
          to-email: shailamore.qa@gmail.com,shailamore.bis@gmail.com
          username: shailamore.qa@gmail.com
          password: ${{ secrets.PASSWORD }}
          subject: Test Email
          body: |
            Hello Everyone,
                This is a test email sent from GitHub Actions for latest checkin
            The Allure report for the latest run in ${{ github.repository }} is available at:
            https://shailamoreqa.github.io/May25API_OrangeHRM/${{ github.run_number }}
            
            Thanks and Regards
            Shaila More
