name: Sprint Development

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      test_cases:
        description: 'Test cases to run (e.g., LoginTests#testLogin+testLogout,SignupTests#testSignup)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Run Selected testCases using maven using workflow
        continue-on-error: true
        run: |
          echo "Running the following test cases:"
          echo "${{ github.event.inputs.test_cases }}"
          mvn test -Dtest="${{ github.event.inputs.test_cases }}"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Reports
        uses: simple-elf/allure-report-action@v1
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          retention_period: 5

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Sending Emails
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.gmail.
